sudo: false
language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev --skip-lock
script:
- pipenv run coverage run application/manage.py test application
- pipenv run coverage report
- pipenv run flake8 application

deploy:
  provider: heroku
  app: meindica-chatbot
  api_key:
    secure: AWjm9ue8A99o+3PO0FmEkSmgNYAHB922Ic/4NOyz2Q2Ns27VD4MWxrZuFbIsasb1shLfyUltb4B8rA1j4t3Xer6r5/vYz/J/2u36CdF2JmQW7y1+h8L3HbS6AtVWyzAFr+a5Ktr9kjBpG3K97l5jaVqvc4gH38gWu2VzpRJ17r5qSeYZezIkD5IVM4suIqU9gYQpEMQ9CmrFkn9Q9zt7y935x85NQkoFJ+zEjY8HeeKPS4NiVZxahaOhWjHuUhYkCfBBiryuvT8g1ySyivXWQkPpF5BOwQecn5tJxLKMLOkb2d2hVbFtpe4HTYo/dT9KgghgYcmo9+ippvIn+IvOqAwmWsycMzqMjnnGDPpLbMClgckn88hRk0j0la2Yae0a6qu/nZEXpFPYzvQj0EVZ9Q7ERl8MSfwKRUdnmDYZ8Mmc3qzJ/Xv7gCrUQJhFhqc9vMc8zvTmmNDEH88PH+DUtKSA/XtPYcfNvIDrSPKMB1j95hLggj+dthMGRrHxJcgStGU/1NfQu638ZXx0Ndu/SXK3lKp+z3yZwrCj9kdt3cJBE/ca4OfiZiNTfqiBV36QfNXrnZxCbnpcN3rDJ/mdVCRMxRaqcJDYRgnt7uFynDRbvx7B9sQhBhJ02OnJgzCDYWNW8/9pz3mZKEk+pXxps2M4/YxU8GNONyJQ3yDC9wI=
