# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.CharField(default='welcome', max_length=50)),
            ],
            options={
                'verbose_name': 'UserState',
                'verbose_name_plural': 'UserStates',
            },
        ),
    ]
