# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_student', models.IntegerField(default=0)),
                ('documents_sheets', models.IntegerField(default=0)),
                ('image_video', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('heavy_game', models.IntegerField(default=0)),
                ('light_games', models.IntegerField(default=0)),
                ('cost_benefit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
