# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heavy_game',
            new_name='heavy_games',
        ),
    ]
