# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomadee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='gpu',
            new_name='has_gpu',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='ssd',
            new_name='has_ssd',
        ),
        migrations.AddField(
            model_name='computer',
            name='is_macbook',
            field=models.BooleanField(default=False),
        ),
    ]
