# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomadee', '0002_auto_20170908_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='thumbnail_url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='computer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computer',
            name='thumbnail',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
